### ISSUE TITLE
Can't reach F-droid or AppStore to dowload the app

### ISSUE THREAD

**Issue by zarevskaya** [blackcandy-org/blackcandy#382]
Hi, 

I can't reach either of them. Do you have the same?

Thanks for all your work!

**Comment by aidewoode** [comment]
For AppStore, I think it'll take some time to publish to all available region.  The only region that Black Candy is unavailable is China, because I don't have ICP number for the app.

For F-droid, I have already submitted to F-droid, but F-droid it's also need some time to show up app on website and client. See: https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by zarevskaya** [comment]
Thanks for the answer :)

I will wait to edit my article.

https://belginux.com/installer-black-candy-avec-docker/
